codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 5%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "test/**/*"
  - "scripts/**/*"
  - "node_modules/**/*"
  - "artifacts/**/*"
  - "cache/**/*"
  - "coverage/**/*"
  - "next/**/*"
  - "**/*.test.js"
  - "**/*.spec.js"
